character_Speed = 3 //Character's movement speed
character_Attack = 5 //Character's attack
character_Armor = 2
character_Health = 10
character_MaxHealth = 10
character_Luck = 1 // Character Luck, 1 = 1% 
character_AttackSpeed = 1
canAttack = 0
canMove = 0
lastDirectionX = 1
lastDirectionY = 1
lastSprite = noone
can_BeHit = 0
moveDir = 0;
can_dash = 0;
hit = 0
can_SpecialAttack = 0
xspd = lengthdir_x(10,moveDir);
yspd = lengthdir_y (10,moveDir);